# ── python/analysis/gradcam.py ──
"""
Grad-CAM Explainability for Robot Decisions
=============================================
Visual explanations for robot action decisions.

Why this matters for embodied AI:
- Safety: "Why did the robot choose this grasp point?"
- Debugging: "What in the scene triggered the navigation decision?"
- Trust: Factory operators need to understand robot behavior
- Compliance: Safety audits require interpretable AI decisions
"""

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from typing import Optional, Tuple


class GradCAM:
    """Gradient-weighted Class Activation Mapping for robot vision models."""

    def __init__(self, model: nn.Module, target_layer: Optional[nn.Module] = None):
        self.model = model
        self.model.eval()
        self.gradients = None
        self.activations = None

        if target_layer is None:
            target_layer = self._auto_detect_target_layer(model)
        self.target_layer = target_layer

        self._register_hooks()

    def _auto_detect_target_layer(self, model: nn.Module) -> nn.Module:
        """Auto-detect last conv layer."""
        for m in reversed(list(model.modules())):
            if isinstance(m, nn.Conv2d):
                return m
        raise ValueError("No Conv2d layer found in model")

    def _register_hooks(self):
        def forward_hook(module, input, output):
            self.activations = output.detach()

        def backward_hook(module, grad_input, grad_output):
            self.gradients = grad_output[0].detach()

        self.target_layer.register_forward_hook(forward_hook)
        self.target_layer.register_full_backward_hook(backward_hook)

    def generate(self, x: torch.Tensor, target_class: Optional[int] = None) -> np.ndarray:
        """Generate Grad-CAM heatmap.

        Args:
            x: input tensor [1, C, H, W]
            target_class: class to explain (None = predicted class)

        Returns:
            Heatmap as numpy array [H, W] in [0, 1]
        """
        self.model.zero_grad()
        output = self.model(x)

        if target_class is None:
            target_class = output.argmax(dim=1).item()

        # Backward
        one_hot = torch.zeros_like(output)
        one_hot[0, target_class] = 1
        output.backward(gradient=one_hot, retain_graph=True)

        # Weighted combination
        if self.gradients is None or self.activations is None:
            return np.zeros(x.shape[2:], dtype=np.float32)

        weights = self.gradients.mean(dim=(2, 3), keepdim=True)  # [1, C, 1, 1]
        cam = (weights * self.activations).sum(dim=1, keepdim=True)  # [1, 1, H, W]
        cam = F.relu(cam)

        # Normalize to [0, 1]
        cam = cam.squeeze().cpu().numpy()
        if cam.max() > cam.min():
            cam = (cam - cam.min()) / (cam.max() - cam.min())
        return cam.astype(np.float32)

    def overlay(self, image: np.ndarray, heatmap: np.ndarray, alpha: float = 0.4) -> np.ndarray:
        """Overlay heatmap on image."""
        try:
            import cv2
            h, w = image.shape[:2]
            heatmap_resized = cv2.resize(heatmap, (w, h))
            heatmap_color = cv2.applyColorMap((heatmap_resized * 255).astype(np.uint8), cv2.COLORMAP_JET)
            return cv2.addWeighted(image, 1 - alpha, heatmap_color, alpha, 0)
        except ImportError:
            return image


def generate_robot_explanation(
    heatmap: np.ndarray,
    action: str,
    confidence: float,
    scene_description: Optional[dict] = None,
) -> str:
    """Generate human-readable explanation for robot action.

    Args:
        heatmap: Grad-CAM heatmap
        action: robot action taken (e.g., "grasp", "navigate", "inspect")
        confidence: model confidence
        scene_description: optional scene metadata

    Returns:
        Structured explanation text
    """
    h, w = heatmap.shape
    center_focus = heatmap[h//4:3*h//4, w//4:3*w//4].mean()
    edge_focus = (heatmap.mean() - center_focus * 0.25) / 0.75

    lines = [
        f"## Robot Action Explanation",
        f"",
        f"**Action**: {action}",
        f"**Confidence**: {confidence:.1%}",
        f"",
        f"### Visual Attention",
    ]

    if center_focus > edge_focus:
        lines.append(f"- Model focused on **central region** (primary object)")
    else:
        lines.append(f"- Model focused on **peripheral region** (context/safety)")

    if scene_description:
        lines.append(f"")
        lines.append(f"### Scene Context")
        for key, val in scene_description.items():
            lines.append(f"- {key}: {val}")

    lines.append(f"")
    lines.append(f"*Generated by Embodied-FL Grad-CAM explainability module.*")
    return "\n".join(lines)
